"""
Extract reference report PDFs into a TypeScript module so the system
prompt can include them as structural blueprints.

Run when references/ PDFs change:
    python scripts/extract-references.py
"""

import io
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

from pypdf import PdfReader

ROOT = Path(__file__).parent.parent
REFS_DIR = ROOT / "references"
OUT = ROOT / "src" / "lib" / "reports" / "reference-content.ts"


def extract_pdf_text(path: Path) -> str:
    reader = PdfReader(str(path))
    parts = []
    for i, page in enumerate(reader.pages):
        text = (page.extract_text() or "").strip()
        if text:
            parts.append(f"--- PAGE {i + 1} ---\n{text}")
    return "\n\n".join(parts)


def escape_for_template(text: str) -> str:
    """Escape backticks and ${} so the text can sit inside a JS template literal."""
    return (
        text.replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
    )


def main():
    refs = [
        ("cii_foods", "reference-cii-foods.pdf"),
        ("planitroi", "reference-planitroi.pdf"),
        ("cable_dahmer", "reference-cable-dahmer.pdf"),
    ]

    extracted = {}
    for slug, filename in refs:
        path = REFS_DIR / filename
        if not path.exists():
            print(f"[skip] {filename} not found")
            continue
        text = extract_pdf_text(path)
        extracted[slug] = text
        print(f"[OK] {slug}: {len(text)} chars, {text.count('--- PAGE')} pages")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by scripts/extract-references.py",
        "// Source PDFs in references/ folder. DO NOT edit by hand.",
        "// Re-run the script after changing the PDFs.",
        "",
    ]
    for slug, text in extracted.items():
        safe = escape_for_template(text)
        lines.append(f"export const REFERENCE_{slug.upper()} = `{safe}`;")
        lines.append("")

    lines.append("export const REFERENCES = {")
    for slug in extracted:
        lines.append(f"  {slug}: REFERENCE_{slug.upper()},")
    lines.append("} as const;")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
