// AUTO-GENERATED by scripts/extract-references.py
// Source PDFs in references/ folder. DO NOT edit by hand.
// Re-run the script after changing the PDFs.

export const REFERENCE_CII_FOODS = `--- PAGE 1 ---
Leveraging Generative AI for 
Operational Excellence & 
EBITDA Expansion
CII Foods (Cereal Ingredients, Inc.) · Executive Leadership Team · March 2024 
· Confidential

--- PAGE 2 ---
Company at a Glance
~$184M Revenue
Midpoint estimate · Privately held
~395 Employees
Two facilities · 7 production lines · 
24/7
Core Products
Particulates, granola, panning, 
Nutri-Crisps®, plant proteins
Strategic Inflection Point
Founder Robert W. Hatch 
passed January 2025. 
Combined with a $24M capital 
expansion and intensifying AI-
enabled competition, the 
moment demands 
transformation.

--- PAGE 3 ---
The Opportunity in Numbers
$184M
Revenue Base
3%
Current EBITDA Margin
Industry avg: 2.5–4%
$16M
Annual Savings 
Potential
High-end estimate
290%
EBITDA Improvement
Over 3 years
EBITD A Lo w $M
 EBITD A High $M
0
5
1 0
1 5
2 0
B a s e l i n e Y e a r  1 Y e a r  2 Y e a r  3
Y e a r

--- PAGE 4 ---
CURRENT LANDSCAPE
Why Act Now
Margin Pressure
EBITDA 2.5–4% · Food input inflation +6% projected · Gross 
margins constrained by commodity volatility
Labor Escalation
24/7 shift premiums · Scarce food scientists & extrusion 
operators · Manual changeover management
Operational Complexity
SKU proliferation · BRC/FSMA/HACCP manual documentation · 
14-person sustainability committee
Scale Disadvantage
$184M vs. $900M+ competitors · No public AI/automation 
initiatives · Window to act is narrowing

--- PAGE 5 ---
AI IMPACT AREAS
Where AI Transforms CII Foods
SG&A Functions
Finance & 
Accounting
7.5-day faster close · 
60–70% AP automation · 
$1.13M–$1.63M value
Sales & Marketing
25–47% productivity 
gains · AI proposals · 
$4.05M–$6.00M value
Customer Service
60–70% inquiry 
deflection · 24/7 AI agent 
· $450K–$600K value
HR & Legal
30–40% faster hiring · 
compliance automation · 
$650K–$870K value
Operations
Production & 
Quality
97–99% defect detection 
· 10–15% throughput 
gain · $2.77M–$3.69M 
value
Supply Chain
20–50% forecast 
accuracy · 10–20% 
inventory reduction · 
$1.07M–$1.86M value
R&D Acceleration
30–40% faster 
formulation · $3.68M–
$5.52M revenue impact
Sustainability
80–85% less data 
collection · automated 
ESG reporting · $445K–
$671K value

--- PAGE 6 ---
FINANCIAL IMPACT
Consolidated AI Value Summary
Function Annual Value Timeline
Finance & Accounting $1.13M – $1.63M 6–12 months
HR & Talent $350K – $455K 6–12 months
Sales & Marketing $4.05M – $6.00M 12–18 months
Customer Service $450K – $600K 6–9 months
Legal & Compliance $300K – $415K 9–15 months
Production & Quality $2.77M – $3.69M 12–24 months
Supply Chain $1.07M – $1.86M 12–18 months
R&D (Revenue Impact) $4.11M – $6.13M 18–36 months
Sustainability $445K – $671K 6–12 months
TOTAL IMPACT $14.66M – $21.42M 36 months
Investment Required: $1.8M–$2.4M over 36 months · Payback: 6–9 months · 3-Year ROI: 1,122–1,192%

--- PAGE 7 ---
IMPLEMENTATION ROADMAP
Three-Phase Transformation
1
Phase 1 · Days 1–90
Fast Wins
Executive AI immersion · Invoice automation · Sales proposal AI 
· Customer service chatbot · ESG dashboard
Investment: $185K–$280K
Value: $300K–$470K run-rate
2
Phase 2 · Months 4–12
Scale & Integrate
Enterprise AI platform · Computer vision QC · Supply chain 
forecasting · R&D formulation AI · Sales enablement
Investment: $1.29M–$1.92M
Value: $8.5M–$12.8M run-rate
3
Phase 3 · Months 13–36
Optimize & Lead
AI Center of Excellence · Predictive maintenance · Augmented 
R&D lab · Customer portal · Full optimization
Investment: $1.58M–$2.17M
Value: $14.7M–$21.4M run-rate

--- PAGE 8 ---
RISK MANAGEMENT
Key Risks & Mitigations
1 Fragmented Adoption
Prob: HIGH · Governance framework + Steering Committee approval + enterprise platform by Month 8
2 Data Quality Gaps
Prob: MEDIUM-HIGH · Data readiness assessment in Phase 1 · Prioritize high-data-availability use cases first
3 Change Resistance
Prob: MEDIUM · AI as copilot, not replacement · No layoffs commitment · Tiered training for all 395 employees
4
Food Safety Failures
Impact: CATASTROPHIC · Human-in-the-loop mandatory · Conservative confidence thresholds · Rigorous validation 
protocols
5 Vendor Lock-In
Prob: MEDIUM · Open APIs · Multi-vendor strategy · Data portability in contracts · Quarterly tech reviews
6 Cybersecurity
Impact: $2M–$10M · SOC 2 / ISO 27001 required · Private cloud for formulations · Annual penetration testing

--- PAGE 9 ---
ENTERPRISE VALUE
The Valuation Transformation
Today
$5.52M EBITDA × 4.5–5.5x
= $24.8M – $30.4M
Year 3 (Post-AI)
$16.8M–$21.5M EBITDA × 
5.5–6.5x
= $92.4M – $139.8M
Enterprise Value Created: 
$67.6M – $109.4M on 
$1.8M–$2.4M investment
Strategic Optionality
Remain independent with 
top-quartile 9.1–11.7% 
EBITDA margins
Attract strategic or financial 
buyers at premium multiples
Scale to $250M–$300M 
revenue without proportional 
SG&A growth

--- PAGE 10 ---
CALL TO ACTION
The Choice Is Clear
❌ Option A: Status Quo
Margin erosion · Talent attrition · Valuation stagnation · 
Acquisition target within 3–5 years
✅ Option B: AI Transformation
$11.3M–$16.0M EBITDA uplift · 9.1–11.7% margins · 
$67.6M–$109.4M enterprise value created
Immediate Next Steps — Week 1
01
Day 1–3
CEO convenes leadership · Secure board endorsement · Commit 
to 3-year investment plan
02
Week 1
Engage AI consulting partner · Assign Phase 1 lead (COO/CFO) · 
Allocate $185K–$280K budget
03
Week 1–2
CEO-wide communication: AI as copilot, not replacement · Invite 
employee input
04
Week 2–4
Select 3–4 Phase 1 pilots · Begin Executive Immersion training
"The transformation begins now. The opportunity is quantified. The roadmap is clear."`;

export const REFERENCE_PLANITROI = `--- PAGE 1 ---
Strategic Growth Through AI
Leveraging Generative AI for Operational Excellence at PlanITROI

--- PAGE 2 ---
COMPANY OVERVIEW
PlanITROI at a Glance
$26.1M
Annual Revenue
115
Employees
87
Countries Served
24
Years Operating
Leading IT Asset Disposition provider transforming asset recovery into 
revenue generation while advancing digital inclusion and sustainability.
Recent Investment: $9M Center of Excellence facility in Youngsville, NC 
with 1M units/year capacity.

--- PAGE 3 ---
The Opportunity
First-Mover Advantage
ITAD industry lags in AI adoption
—creating differentiation 
opportunity
Efficiency Gap
38-person sales team generating 
$687K per rep vs. $1-2M+ 
industry benchmark
Margin Expansion
Transform from 12-15% to 35-45% EBITDA margin through AI 
optimization

--- PAGE 4 ---
FINANCIAL IMPACT
Projected EBITDA Uplift
$3.3M-$4.2M
Annual Savings Potential
Representing 100-135% increase in bottom-line 
profitability
SG&A Functions
25-30% reduction: $2.6M-$3.1M annually
Logistics & Supply Chain
10-15% reduction: $420K-$630K annually
Customer Service
20-30% reduction: $320K-$480K annually

--- PAGE 5 ---
AI Applications Across Functions
Finance & Accounting
Automated reporting, revenue-
share calculations, invoice 
processing
Impact: 25-35% labor 
reduction, $413K-$578K 
savings
Sales & Marketing
Proposal automation, lead 
scoring, CRM intelligence, 
content generation
Impact: 30-40% efficiency gain, 
$950K-$1.2M savings
Customer Service
AI chatbots, automated 
certificates, 24/7 support, self-
service portals
Impact: 50-60% inquiry 
deflection, $132K-$198K 
savings
Supply Chain
Route optimization, demand 
forecasting, predictive asset 
valuation
Impact: 10-15% cost reduction, 
$420K-$630K savings

--- PAGE 6 ---
PHASE 1
Fast Wins: First 90 Days
01
Executive AI Training
One-day intensive workshop for leadership 
alignment
02
Sales Proposal Automation
Reduce proposal time from 15-20 hours to 
3-5 hours
03
Finance Reporting Automation
Save 30-40 hours monthly on board 
packages
04
Customer Service Chatbot
Deflect 40-50% of Tier 1 support tickets
05
AI Governance Framework
Establish policies, standards, and ROI tracking
Investment
$100K-$165K
Expected ROI
$650K-$900K annually (6-9x return)
Payback Period
2-3 months

--- PAGE 7 ---
3-Year Financial Transformation
$0.00
$15,000,000.00
$30,000,000.00
$45,000,000.00
Revenue EBITDA EBITDA Margin
Current Year 3
Cumulative Impact
34%
Revenue growth without proportional headcount increase
300%
EBITDA margin expansion from baseline
Total 3-Year Investment: $1.67M-$2.45M
Net EBITDA Improvement: $5.5M-$9.0M after all investments

--- PAGE 8 ---
Revenue Enhancement Beyond Cost Savings
Improved Asset Pricing
AI-powered dynamic remarketing valuation
+$728K-$1.1M annually
Sales Acceleration
15-20% faster deal closure through automation
+$1.3M-$1.8M incremental
Marketing-Led Growth
3-5x content production, improved nurture
+$2.1M-$3.1M over 18 months
Retention Improvement
AI-powered renewal prediction
+$520K-$780K annually
Total Revenue Uplift Potential: +$4.7M-$6.8M representing 18-26% revenue growth over 18 months

--- PAGE 9 ---
RISK MANAGEMENT
Mitigation Strategies
Fragmented Adoption
Establish AI Center of Excellence with enterprise architecture 
oversight
Data Quality Issues
Phase 0 data audit; invest in Master Data Management
Change Resistance
Transparent "AI augments, doesn't replace" communication; 
reskilling programs
Compliance & Privacy
Legal review of vendors; SOC 2 Type II requirements; annual 
audits

--- PAGE 10 ---
The Time to Act Is Now
Strategic Imperative
AI is not a speculative bet—it's the force multiplier that enables 
PlanITROI to serve 2x the customers, deliver 3x the environmental 
impact, and generate 3-4x the EBITDA.
First-mover advantage window is narrow
Transform from margin-constrained to 
technology-enabled leader
Scale mission-driven impact through operational 
efficiency
"The question is not whether to adopt AI, but how 
quickly PlanITROI can outpace competitors who are 
just beginning to recognize its potential."`;

export const REFERENCE_CABLE_DAHMER = `--- PAGE 1 ---
Generative AI Transformation 
Initiative
Cable Dahmer Automotive Group — Strategic Growth Report

--- PAGE 2 ---
Cable Dahmer at a Glance
60+
Years in Market
Kansas City metro
9
Dealership Locations
MO & KS markets
$240M
Est. Annual Revenue
FY2024
500
Employees
Across 9 locations
28.79%
YoY Growth
Under CEO Ledezma
$4.7B
Transaction Volume
2023
9 OEM franchises: Chevrolet, GMC, Buick, Cadillac, Kia, Chrysler, Dodge, Jeep, Ram — CARFAX 2025 Top-Rated Lifetime Dealer

--- PAGE 3 ---
The Strategic Imperative
The Threat
80% of automotive leads now digital
Competitors achieving 27% higher appointment rates via AI
National consolidators investing heavily in automation
Widening technology gap during critical growth phase
The Opportunity
Target: 15–20 dealership expansion
AI enables non-linear scaling — no proportional headcount 
growth
First-mover advantage in Kansas City market
Preserve family-owned culture while achieving institutional 
excellence
AI adoption is not optional — it is a competitive survival requirement.

--- PAGE 4 ---
Quantified EBITDA Uplift
SG&A Cost Reduction
$3.3M – $4.8M annually
1.4–2.0% of revenue
Sales Productivity
$1.8M – $3.0M uplift
37% lead conversion increase
Service Efficiency
$1.2M – $1.8M impact
25% advisor productivity gain
Turnover Reduction
$800K – $1.2M savings
67% sales / 25% service turnover
$9.9M
Total Annual Impact
Steady-state (Year 2–3)
29%
EBITDA Uplift
6–8% →  9.2–12% margins
594%
3-Year Net ROI
On AI investments

--- PAGE 5 ---
CURRENT LANDSCAPE
Industry Pressures & 
Competitive Gap
Industry Headwinds
Net profit margins: 3% industry 
average
SG&A: 70375% of gross profit
Sales turnover: 67% annually 4 
$1.031.2M cost
Consumer expects response in 
<5 minutes
Competitor Benchmarks
CarMax: $150M SG&A reduction 
target, 30% chatbot containment
Group 1: SG&A reduced 75.6% 
→ 67.4% of GP
Johnson Honda: 47% more units 
sold via AI chatbots
Cable Dahmer: No disclosed AI 
initiatives as of Feb 2025

--- PAGE 6 ---
AI Applications Across SG&A Functions
Finance & Accounting
Automated invoice processing, AI financial reporting, 
cash flow forecasting
Savings: $240K–$400K/yr
HR & Talent
AI recruiting chatbot, intelligent onboarding, retention 
analytics
Savings: $530K–$860K/yr
Sales & Marketing
24/7 lead qualification, automated proposals, content 
generation
Impact: $1.8M–$3.0M/yr
Customer Service / BDC
AI scheduling, predictive maintenance outreach, after-
hours capture
Impact: $1.2M–$1.8M/yr
Legal & Compliance
Contract review, F&I document automation, regulatory 
monitoring
Savings: $80K–$160K/yr
IT & Administration
Help desk automation, data entry AI, cybersecurity 
monitoring
Savings: $360K–$540K/yr

--- PAGE 7 ---
Three-Phase Transformation Roadmap
Fast Wins
0–90 days · $97K–
196K invest · $210K–
420K impact
Scale & Integrate
6–12 months · 
$496K–956K invest · 
$3.67M–6.23M 
impact
Govern & Lead
12–24 months · 
$750K–1.35M invest · 
transformational 
advantage
Phase 1 ROI
108–217% annual return
Phase 2 ROI
383–651% annual return
3-Year Net ROI
365–594% total return

--- PAGE 8 ---
PHASE 1 — FIRST 90 DAYS
Fast Win Initiatives
01
AI Executive Immersion Training
Full leadership team workshop — AI 
fundamentals, live demos, governance 
framework. $15K–25K
02
AI Chatbot Pilot (2 Locations)
24/7 lead qualification & appointment 
scheduling on website + Facebook. $24K–
50K →  $150K–300K impact
03
AP Automation Quick Win
AI invoice processing, 3-way matching, 
automated approvals. $27K–60K →  $20K–
40K savings
04
HR Recruiting & Knowledge Chatbot
Candidate screening, employee HR self-service. $26K–51K → 
$40K–80K savings
05
AI Use Policy & Governance
Acceptable use policy, vendor criteria, AI Steering Committee 
charter. $5K–10K

--- PAGE 9 ---
Risk Mitigation Framework
Low Adoption
CEO sponsorship, mandatory training, manager bonuses 
tied to AI adoption metrics
Data Security
SOC 2 / ISO 27001 vendors only, AI Use Policy enforcement, 
data anonymization protocols
AI Hallucinations
Strict chatbot guardrails, human-in-the-loop for high-stakes 
interactions, weekly transcript review
Poor Integration
Integration-first vendor selection, dedicated solution 
architect, Phase 1 pilot validation
Employee Displacement
"Augmentation, not replacement" — AI funds expansion, 
creating net new jobs; attrition-based optimization
Regulatory Risk
External automotive compliance counsel reviews all F&I AI; 
human final authority on credit decisions

--- PAGE 10 ---
The Call to Action
"We will scale to 15320 dealerships not through incremental headcount 
growth, but through exponential capability growth powered by generative 
AI 4 while maintaining the trust and community commitment of a family-
owned business."
Weeks 1–2
Executive review, board approval, appoint AI Steering Committee
Weeks 3–4
Issue RFPs for chatbot, AP automation, HR chatbot; draft AI Use Policy
Weeks 5–8
Select vendors, launch pilots at 2 locations, begin executive training
Weeks 9–12
Review ROI, go/no-go on Phase 2, communicate wins to organization
Investment: $1.34–2.5M over 24 months → $6.1–9.9M annual 
steady-state value. The cost of delay is measured in millions 
annually.
Need more info? Contact Dani@ChiefAIOfficer.com`;

export const REFERENCES = {
  cii_foods: REFERENCE_CII_FOODS,
  planitroi: REFERENCE_PLANITROI,
  cable_dahmer: REFERENCE_CABLE_DAHMER,
} as const;
