-- =============================================================
-- Seed: GHL Tags choices (Dropdown Configuration page)
-- =============================================================
-- 427 distinct GHL tags imported from the ops CSV
-- ("Supporting Information - GHL Tags TRIMMED.csv"). Task Name -> value,
-- Status -> mapped status, Notes -> notes. Status mapping:
--   purchased/legacy/keep/finished/active workflow -> Keep
--   to remove from system -> To Remove | removed from system -> Removed
--   unknown -> Unknown
-- Duplicates collapsed to one row (Keep occurrence preferred, else first);
-- the two conflicts (cert - ai consultant, cert - ai executive) resolved to Keep.
-- Re-runnable: ON CONFLICT re-applies the CSV's status/notes (overwrites manual
-- edits to those two fields on re-import; switch to DO NOTHING to preserve them).
-- =============================================================

INSERT INTO "automation_dropdown_choices" ("column_key", "value", "status", "notes") VALUES
  ('ghl_tags', '* ai authority', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', '* ai authority workshop', 'Unknown', '(KEEP - ai authority is still supported) ai auth welcome email'),
  ('ghl_tags', '#aiintegrator2025', 'Unknown', NULL),
  ('ghl_tags', '#caio_cert_2026', 'Unknown', NULL),
  ('ghl_tags', '#client', 'Unknown', NULL),
  ('ghl_tags', '#miller-group-feb-2026', 'Unknown', NULL),
  ('ghl_tags', '#paymentplan', 'Unknown', NULL),
  ('ghl_tags', '#ypo_feb_2026', 'Unknown', NULL),
  ('ghl_tags', '1 day challenge 17dec24 lp', 'Removed', NULL),
  ('ghl_tags', '1-day challenge 2/18/25', 'Removed', NULL),
  ('ghl_tags', '1-day challenge 2/18/25 existing', 'Removed', NULL),
  ('ghl_tags', '1-day challenge 2/25/25', 'Removed', NULL),
  ('ghl_tags', '1-day challenge 3/11/25', 'Removed', NULL),
  ('ghl_tags', '1-day challenge 3/4/25', 'Removed', NULL),
  ('ghl_tags', '2-day challenge linkedin ad', 'Removed', NULL),
  ('ghl_tags', '2-day challenge nov 2024', 'Removed', NULL),
  ('ghl_tags', '23-day-active', 'Unknown', NULL),
  ('ghl_tags', '23-day-complete', 'Unknown', NULL),
  ('ghl_tags', '23-day-no-response', 'Unknown', NULL),
  ('ghl_tags', '23-day-replied', 'Unknown', NULL),
  ('ghl_tags', '3 day challenge registrants', 'Removed', NULL),
  ('ghl_tags', '3-day-challenge-completed', 'Removed', NULL),
  ('ghl_tags', '3-day-challenge-registrants', 'Removed', NULL),
  ('ghl_tags', '3-day-challenge-registration-follow-up', 'Removed', NULL),
  ('ghl_tags', 'abm outreach', 'Keep', NULL),
  ('ghl_tags', 'abm-clay-oc-construction', 'Keep', NULL),
  ('ghl_tags', 'abm-construction-associations', 'Keep', NULL),
  ('ghl_tags', 'add to click up', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'admin', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'affiliate-affiliate signup', 'Unknown', '(KEEP - affiliate)'),
  ('ghl_tags', 'affiliate-current affiliate', 'Unknown', '(KEEP - affiliate)'),
  ('ghl_tags', 'affiliate-potential affiliate', 'Unknown', '(KEEP - affiliate)'),
  ('ghl_tags', 'affiliate-removed affiliate', 'Unknown', '(KEEP - affiliate)'),
  ('ghl_tags', 'affiliate-signup', 'Keep', '(TO REMOVE - No Workflow) (KEEP - affiliate)'),
  ('ghl_tags', 'ai aggression detected', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai appointment booked', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai booking error', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai bot detected', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai business integrator', 'Unknown', NULL),
  ('ghl_tags', 'ai consultant', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai consultant course complete', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai custom detected', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai enablement bundle', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai enablement bundle - cart abandon', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai executive', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai executive course complete', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai followup detected', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai goodbye detected', 'Unknown', NULL),
  ('ghl_tags', 'ai human handoff detected', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai insiders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai insiders trial active', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai objectives complete', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai off', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'AI Ownership - Active Sequence', 'Unknown', NULL),
  ('ghl_tags', 'AI Ownership - Booked Call', 'Unknown', NULL),
  ('ghl_tags', 'ai responded', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai spam detected', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai value discovery session', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai-governance reminders', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ai-productivity webclass', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'air.ai call', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'alignment-services-submission', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'alignment-team-submission', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'alumni', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'am-call-connected', 'Keep', NULL),
  ('ghl_tags', 'appointment-booked', 'Keep', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'appointment-no-show', 'Keep', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'assessment survey', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'asset_sent_30d', 'Unknown', NULL),
  ('ghl_tags', 'asset_sent_ai_map', 'Unknown', NULL),
  ('ghl_tags', 'asset_sent_caio_30', 'Unknown', NULL),
  ('ghl_tags', 'asset_sent_council', 'Unknown', NULL),
  ('ghl_tags', 'assign to kathryn', 'Unknown', NULL),
  ('ghl_tags', 'b2b_credegroup', 'Unknown', '(KEEP - b2b)'),
  ('ghl_tags', 'b2b_deb', 'Unknown', '(KEEP - b2b)'),
  ('ghl_tags', 'b2b_frazerbilt', 'Unknown', '(KEEP - b2b)'),
  ('ghl_tags', 'b2b_group', 'Keep', NULL),
  ('ghl_tags', 'b2b_immatics', 'Unknown', '(KEEP - b2b)'),
  ('ghl_tags', 'b2b_johnburnscc', 'Unknown', NULL),
  ('ghl_tags', 'b2b_pella', 'Unknown', NULL),
  ('ghl_tags', 'b2b-ai-exec-onboarded', 'Unknown', NULL),
  ('ghl_tags', 'b2b-checkin-roadshow-louisville', 'Unknown', NULL),
  ('ghl_tags', 'b2b-const-assoc-austin', 'Unknown', NULL),
  ('ghl_tags', 'b2b-const-assoc-dallas', 'Unknown', NULL),
  ('ghl_tags', 'b2b-const-assoc-houston', 'Unknown', NULL),
  ('ghl_tags', 'b2b-const-assoc-ypo-kc', 'Unknown', NULL),
  ('ghl_tags', 'b2b-construction-austin', 'Unknown', NULL),
  ('ghl_tags', 'b2b-construction-dallas', 'Unknown', NULL),
  ('ghl_tags', 'b2b-construction-houston', 'Unknown', NULL),
  ('ghl_tags', 'b2b-construction-ypo-kc', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow', 'Keep', '(KEEP - b2b)'),
  ('ghl_tags', 'b2b-registered-roadshow-atlanta', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow-austin', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow-dallas', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow-houston', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow-kc', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow-kc-ypo', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow-newark', 'Unknown', NULL),
  ('ghl_tags', 'b2b-registered-roadshow-rochester', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-atlanta', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-austin', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-austin-don''t touch!!!', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-dallas', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-dallas-don''t touch!!!', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-houston', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-houston-don''t touch!!!', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-kc', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-kc-ypo', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-louisville', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-newark', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-oc', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-reminder', 'Keep', NULL),
  ('ghl_tags', 'b2b-roadshow-reminder-austin', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-reminder-dallas', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-reminder-houston', 'Unknown', NULL),
  ('ghl_tags', 'b2b-roadshow-rochester', 'Unknown', NULL),
  ('ghl_tags', 'b2b-temp-roadshow', 'Keep', '(KEEP - b2b)'),
  ('ghl_tags', 'b2b-vistage-chicago', 'Keep', NULL),
  ('ghl_tags', 'b2b-vistage-houston', 'Unknown', NULL),
  ('ghl_tags', 'b2b-vistage-kc', 'Unknown', NULL),
  ('ghl_tags', 'b2b-vistage-louisville', 'Unknown', NULL),
  ('ghl_tags', 'b2b-ypo-kc', 'Keep', NULL),
  ('ghl_tags', 'b2c reactivation - end', 'Unknown', NULL),
  ('ghl_tags', 'b2c reactivation - replied', 'Unknown', NULL),
  ('ghl_tags', 'b2c reactivation - start', 'Unknown', NULL),
  ('ghl_tags', 'b2c-course-caio-enrolled', 'Keep', NULL),
  ('ghl_tags', 'b2c-course-caio-graduate', 'Keep', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'b2c-in-workflow-2025-ai-wealth-blueprint', 'Keep', NULL),
  ('ghl_tags', 'b2c-in-workflow-2025-unleash-ai-for-business', 'Unknown', '(KEEP - b2c)'),
  ('ghl_tags', 'b2c-purchased-2025-ai-wealth-blueprint', 'Keep', NULL),
  ('ghl_tags', 'b2c-purchased-ai-cert-2500', 'Keep', NULL),
  ('ghl_tags', 'b2c-registered-2025-ai-wealth-blueprint', 'Keep', NULL),
  ('ghl_tags', 'b2c-registered-2025-unleash-ai-for-business', 'Unknown', '(KEEP - b2c)'),
  ('ghl_tags', 'b2c-registered-ai-consulting-business-blueprint', 'Unknown', NULL),
  ('ghl_tags', 'b2c-registered-ai-governance', 'Keep', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'b2c-registered-challenge', 'Keep', NULL),
  ('ghl_tags', 'b2c-registered-challenge-vip', 'Keep', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'b2c-showup-challenge', 'Keep', NULL),
  ('ghl_tags', 'back-to-dani', 'Unknown', NULL),
  ('ghl_tags', 'batch-a-3-11', 'Unknown', NULL),
  ('ghl_tags', 'batch-b-3-11', 'Unknown', NULL),
  ('ghl_tags', 'batch-c-3-11', 'Unknown', NULL),
  ('ghl_tags', 'big promise sequence', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'blackfriday', 'Unknown', NULL),
  ('ghl_tags', 'booked call - cancelled', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'booked call - no show [iconic]', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'booked call [iconic]', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'booked followup call', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'bucket_1', 'Unknown', NULL),
  ('ghl_tags', 'bucket_2', 'Unknown', NULL),
  ('ghl_tags', 'bucket_3', 'Unknown', NULL),
  ('ghl_tags', 'caio calendar.com', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio certificate | book an interview', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio certificate book a call', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio certification', 'Unknown', '(KEEP - Onboarding Email) welcome email'),
  ('ghl_tags', 'caio course $995 - cart abandon', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio course complete', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio in training', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio interview canceled', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'caio live', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio live - not going', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio live reminders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio_0-prospect-candidate', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio_1-qualified-candidate', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio_3-prospect-employer', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio_4-qualified-employer', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio_alumni', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'caio_cert_2025', 'Unknown', NULL),
  ('ghl_tags', 'caio_community', 'Unknown', '(KEEP - Tags for new course purchasers)'),
  ('ghl_tags', 'caio_course_access', 'Unknown', '(KEEP - Course Emails)'),
  ('ghl_tags', 'caio-sponsorship', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'caiocert', 'Unknown', NULL),
  ('ghl_tags', 'caiocert2025', 'Unknown', NULL),
  ('ghl_tags', 'calendar overload', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'call-answered', 'Unknown', NULL),
  ('ghl_tags', 'cert - ai consultant', 'Keep', 'consultant welcome email'),
  ('ghl_tags', 'cert - ai executive', 'Keep', 'exec welcome email'),
  ('ghl_tags', 'cert lead', 'Unknown', NULL),
  ('ghl_tags', 'challenge reminder', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'challenge waitlist', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'chief ai officer', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'circle - invited 27nov2024', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'circle - members 27nov24', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'circle-community-invited', 'Unknown', NULL),
  ('ghl_tags', 'clay_enriched', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'client offboarded [iconic]', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'client onboarded [iconic]', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'comple', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'consulting blueprint reminders', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'contact_us', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'couldn''t find caller name', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'course', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'csignup325', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'curtis', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'custom_value_trigger', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'delete conversation', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'delete ticket', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'discovery call response', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'discovery-active', 'Unknown', NULL),
  ('ghl_tags', 'dnct', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'donotcontact - our choice [iconic]', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'donotcontact [iconic]', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'donotemail [iconic]', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'dormant-nurture', 'Unknown', NULL),
  ('ghl_tags', 'email event - bounced', 'Keep', NULL),
  ('ghl_tags', 'email event - clicked', 'Keep', NULL),
  ('ghl_tags', 'email event - complained of spam', 'Keep', NULL),
  ('ghl_tags', 'email event - opened', 'Keep', NULL),
  ('ghl_tags', 'email event - unsubscribed', 'Keep', NULL),
  ('ghl_tags', 'email_consumer', 'Unknown', NULL),
  ('ghl_tags', 'email_corporate', 'Unknown', NULL),
  ('ghl_tags', 'email-framework-replied', 'Unknown', NULL),
  ('ghl_tags', 'email-replied', 'Unknown', NULL),
  ('ghl_tags', 'engaged_email_7', 'Unknown', NULL),
  ('ghl_tags', 'engaged_vip', 'Unknown', NULL),
  ('ghl_tags', 'exec cert path forward', 'Unknown', '(KEEP - cert)'),
  ('ghl_tags', 'f1_view book call', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1_view confirmation page', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1_view downsell', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1_view interested', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1_view q1', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1_view q2', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1b_view book a call', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1b_view confirmation page', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1b_view downsell', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1b_view formless', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1b_view q1', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1b_view q2', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1c_view book a call', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1c_view confirmation page', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1c_view downsell', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1c_view formless', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1c_view q1', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1c_view q2', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'f1c_view vsl', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'facebook', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'facebook form submission', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'faculty', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'failed payment', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'fb', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'fb_ad_leadform to vsl', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'feedback_group', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'fellow', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'followup-linkedin', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'followup-rb2b', 'Unknown', '(KEEP - rb2b)'),
  ('ghl_tags', 'form - ai authority close', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'formless submission', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'friday', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'full-batch-b2c-3-11', 'Unknown', NULL),
  ('ghl_tags', 'fully_onboarded', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'gmb', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'google quiz ad', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'google-calendar-invite-sent', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'high', 'Unknown', NULL),
  ('ghl_tags', 'high-abm-sequence-complete', 'Unknown', NULL),
  ('ghl_tags', 'high-icp-lead-engaged', 'Unknown', NULL),
  ('ghl_tags', 'high-priority-touch', 'Unknown', NULL),
  ('ghl_tags', 'hiring', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic - possible self generated lead - ben', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic - possible self generated lead - chris ross', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai - engaged', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai - engaged - email', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai - engaged - fbm', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai - engaged - igm', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai - engaged - live chat website widget', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai - engaged - sms', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai - prevent engagement', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai booking', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai ig', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai kill switch', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'iconic ai lead', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai lead disqualified', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai new lead', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai sms', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'iconic ai unsubscribed', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'iconic linkedin source', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'import from fb ads lp 14dec2024', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'import from fb ads lp 20dec2024', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'incubator', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'initial outreach', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'instagram', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'instantly campaign', 'Unknown', NULL),
  ('ghl_tags', 'interview booking questions-1', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'invoices/receipts solved', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'legacy-iconic', 'Keep', NULL),
  ('ghl_tags', 'li-followup', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'lifetime', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'login/access issues', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'low', 'Unknown', NULL),
  ('ghl_tags', 'lowmed-abm-sequence-complete', 'Unknown', NULL),
  ('ghl_tags', 'lp - workflow step 2 clean up', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'lp-fb import 01-19jan2025', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'manual payment follow-up', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'medium', 'Unknown', NULL),
  ('ghl_tags', 'memberpress signup', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'moderator', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'monday', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'monday call sub', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'mvp', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'name via lookup', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'new hire - team', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'newsletter', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'not booked a call yet [iconic]', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'not going - the ai consulting business blueprint', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'not purchased oto', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'onboarding call scheduled', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'optin - eos conference', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'optin - expert summit conference', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'pattern_blocker_15', 'Unknown', NULL),
  ('ghl_tags', 'pattern_blocker_2', 'Unknown', NULL),
  ('ghl_tags', 'pattern_blocker_x', 'Unknown', NULL),
  ('ghl_tags', 'payment confirmed', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'podc', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'podcast guest', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'podcast subscriber', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'podcast-guest', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'portal accessed', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'post-event-survey', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'pre-event-survey', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'prompt training reminders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'promptvault_user', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'purchased caio course', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'purchased slack community', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'purchased-slo', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'purge', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'pv_beta', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'pv_waitlist', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'qualified', 'Unknown', NULL),
  ('ghl_tags', 'quiz-funnel', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'rb2b', 'Keep', NULL),
  ('ghl_tags', 'rb2b site visitor', 'Keep', NULL),
  ('ghl_tags', 'rb2b_visitor', 'Keep', NULL),
  ('ghl_tags', 'rb2b-enriched', 'Unknown', NULL),
  ('ghl_tags', 'rb2b-site-visitor', 'Keep', NULL),
  ('ghl_tags', 're-entry', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 're-watched video', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'real world ai reminders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'real-world ai', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'real-world ai - not going', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'real-world ai not going', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'real-world ai: the tools & their use cases', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'realworldai reminders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'refund - caio cert', 'To Remove', '(TO REMOVE - No Workflow) (KEEP - cert)'),
  ('ghl_tags', 'refund requests', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'registered attended', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'registered for masterclass', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'registered-not attended', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'remove tag zap trigger', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'replay requests', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'replied via sms', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'replied_no_lens', 'Unknown', NULL),
  ('ghl_tags', 'replied_unanswered', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'reprocess cert leads', 'Unknown', NULL),
  ('ghl_tags', 'requested call', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'requested_ai_map', 'Unknown', NULL),
  ('ghl_tags', 'requested_caio_30', 'Unknown', NULL),
  ('ghl_tags', 'requested_council', 'Unknown', NULL),
  ('ghl_tags', 'requested_impl_30d', 'Unknown', NULL),
  ('ghl_tags', 'requested_impl_30d_tailored', 'Unknown', NULL),
  ('ghl_tags', 'restore correct dnd', 'Unknown', NULL),
  ('ghl_tags', 'ron pearson', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'route-to-23day', 'Unknown', NULL),
  ('ghl_tags', 'route-to-reengagement', 'Unknown', NULL),
  ('ghl_tags', 'service agreement sent', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'skool', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'skool_free', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'slo-cart-abandon', 'Unknown', NULL),
  ('ghl_tags', 'smartcuts', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'sms', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'sms - unsubscribed', 'Unknown', NULL),
  ('ghl_tags', 'sms no fake', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'sms no landline', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'sms yes', 'Keep', NULL),
  ('ghl_tags', 'source-kajabi', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'spam likely', 'Unknown', NULL),
  ('ghl_tags', 'speed-to-lead-success', 'Unknown', NULL),
  ('ghl_tags', 'staff', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'started-caio-calendar.com', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'started-caio-certificate-|-book-an-interview', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'started-caio-certificate-book-a-call', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'started-interview-booking-questions-1', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'stop caio reminders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'subscribed-to-newsletter', 'Unknown', NULL),
  ('ghl_tags', 'Tagged_bucket_2', 'Unknown', NULL),
  ('ghl_tags', 'Tagged_bucket_3', 'Unknown', NULL),
  ('ghl_tags', 'Tags', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'team ai training', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'temp-b2c-adam-lyons', 'Unknown', '(KEEP - b2c)'),
  ('ghl_tags', 'temp-b2c-john-munsell-promo', 'Keep', NULL),
  ('ghl_tags', 'temp-b2c-learn-n8n', 'Keep', NULL),
  ('ghl_tags', 'temp-campaign-loop', 'Unknown', NULL),
  ('ghl_tags', 'temp-louisville-ky', 'Unknown', NULL),
  ('ghl_tags', 'test', 'Keep', NULL),
  ('ghl_tags', 'testing', 'Unknown', NULL),
  ('ghl_tags', 'the-ai-consulting-business-blueprint', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'the-ai-consulting-business-blueprint not going', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'thursday', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'tier 2 | implementor', 'Unknown', NULL),
  ('ghl_tags', 'tier 3 | leadership', 'Unknown', NULL),
  ('ghl_tags', 'transfer_sdr_andrew', 'Unknown', NULL),
  ('ghl_tags', 'transfer_sdr_anna_rose', 'Unknown', NULL),
  ('ghl_tags', 'trigger automation - iconic ai - email engage now manual', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'trigger automation - iconic ai - sms engage now manual', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'tuesday', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'unleash ai for business - mar 2026', 'Unknown', NULL),
  ('ghl_tags', 'upcoming challenges', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'vip', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'vip_ai_insider', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'vip_ai_insider, caio_community', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'vistage', 'Unknown', NULL),
  ('ghl_tags', 'vistage houston', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'watch video 50%', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'watched 20% less', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'watched 50% less', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'webinar form filled', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'website', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'website - ai authority', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'website info submitted', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'wednesday', 'Removed', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'welcome call', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'white paper - industry specific', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'white paper - practical guide', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'white paper - roi', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'white paper - sg&a', 'Unknown', '(NOT SURE)'),
  ('ghl_tags', 'workflow winners - reminders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'workflow winners reminders', 'To Remove', '(TO REMOVE - No Workflow)'),
  ('ghl_tags', 'ypo', 'Unknown', NULL)
ON CONFLICT ("column_key", "value") DO UPDATE SET
  "status" = EXCLUDED."status",
  "notes" = EXCLUDED."notes",
  "updated_at" = now();
